### ISSUE TITLE
Add translation to existing page

### ISSUE THREAD

**Issue by alexfilatov** [kenta-aktsk/translator#6]
Hello @kenta-aktsk! 

Thanks a lot for the great lib! 👍 
I have a question, which is not a bug but mostly a best practice question.

Let's assume I have a `%Page{title, content}` and `%PageTranslation`. 
I have a controller action `create` which creates a Page using PageService approach (Multi) from your `media_sample` example app.
How can I create a translation to existing Page?

How I did that:
1. Added virtual field `page_id` to page schema and to the changeset
2. changed a bit PageService.insert like this:

```
    def insert(changeset, params, locale) do
      Multi.new
      |> (fn(multi) ->
        if Blank.blank?(params["page_id"]) do
          Multi.insert(multi, :page, changeset)
        else
          # getting original page to create translation for
          Ecto.Multi.run(multi, :page, fn get_page ->
            case Repo.get(Page, params["page_id"]) do
               nil -> {:error, nil}
               page -> {:ok, page}
            end
          end)
        end
      end).()
      |> Multi.run(:translation, &(PageTranslation.insert_or_update(Repo, &1[:page], params, locale)))
    end
```

This is works more or less, but I'm wondering is there any better solution to add translations to existing entities?

Thanks a lot in advance!

**Comment by kenta-polyglot** [comment]
Hi @alexfilatov, thank you for your question!

I will answer on weekends. (I've been busy recently...sorry for late reply)

**Comment by kenta-polyglot** [comment]
Hi @alexfilatov, sorry for late reply.

I suppose your situation is like that: there is a Page record, but there is not a PageTranslation record associated to it.

In this situation, I think you should use `update` function in your service class.

Sample code is like below:
```
def update(changeset, params, locale) do
  Multi.new
  |> Multi.update(:page, changeset)
  |> Multi.run(:translation, &(PageTranslation.insert_or_update(Repo, &1[:page], params, locale)))
end
```
`PageTranslation.insert_or_update` function can detect whether PageTranslation record is loaded or not by checking a key of Page record (parent record).

Below is a part of `insert_or_update` function (in `translation_model.ex`)

```
def insert_or_update(repo, parent, parent_params, locale) do
  ...
  if !Map.get(parent, @assoc) || !Ecto.assoc_loaded?(Map.get(parent, @assoc)) do
    ...
    repo.insert(changeset)
  else
    ...
    repo.update(changeset)
  end
end
```

`@assoc`'s default value is `:translation`, so if there is not a `:tranlstaion` key in Page record, `repo.insert` will be called and PageTranslation record will be inserted.

If I'm misunderstanding your situation and your question, sorry for in advance.

**Comment by alexfilatov** [comment]
thank you! :)
